# TypeProf 0.21.11

# Classes
module JsonCanvas
  VERSION: String

  def self.create: -> Canvas
  def self.parse: (untyped json) -> Canvas

  class Canvas
    attr_reader nodes: Array[GenericNode]
    attr_reader edges: Array[Edge]
    def self.parse: (untyped json) -> Canvas
    def initialize: (?Array[GenericNode] nodes, ?Array[Edge] edges) -> void
    def add_text: (**untyped) -> TextNode
    def add_file: (**untyped) -> FileNode
    def add_link: (**untyped) -> LinkNode
    def add_group: (**untyped) -> GroupNode
    def add_edge: (**untyped) -> Edge
    def to_json: -> untyped
    def save: (untyped filename) -> Integer
  end

  class Edge
    attr_accessor id: String
    attr_accessor from_node: String
    attr_accessor from_side: String
    attr_accessor from_end: String
    attr_accessor to_node: String
    attr_accessor to_side: String
    attr_accessor to_end: String
    attr_accessor color: String?
    attr_accessor label: untyped
    def initialize: (**untyped) -> void
    def to_hash: -> Hash[String, String?]
  end

  class GenericNode
    attr_accessor id: String
    attr_accessor x: Integer
    attr_accessor y: Integer
    attr_accessor width: Integer
    attr_accessor height: Integer
    attr_accessor color: String?
    def initialize: (**untyped) -> void
    def default_width: -> Integer
    def default_height: -> Integer
    def to_hash_common: (String `type`) -> (Hash[String, (Integer | String)?])
  end

  class TextNode < GenericNode
    attr_accessor type: String
    attr_accessor text: String
    def initialize: (**untyped) -> void
    def to_hash: -> (Hash[String, (Integer | String)?])
  end

  class FileNode < GenericNode
    attr_accessor type: String
    attr_accessor file: String
    attr_accessor subpath: String?
    def initialize: (**untyped) -> void
    def to_hash: -> (Hash[String, (Integer | String)?])
  end

  class LinkNode < GenericNode
    attr_accessor type: String
    attr_accessor url: String
    def initialize: (**untyped) -> void
    def to_hash: -> (Hash[String, (Integer | String)?])
  end

  class GroupNode < GenericNode
    attr_accessor type: String
    attr_accessor label: String?
    attr_accessor background: String?
    attr_accessor background_style: String?
    def initialize: (**untyped) -> void
    def to_hash: -> (Hash[String, (Integer | String)?])
  end
end
